import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextJS CRUD App",
  description: "Generated by create next app, SSR",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          <nav>
            <Link href='/'>Home</Link>
            <Link href='/create'>Create Task</Link>
            <Link href ='/view'>Task List</Link>
          </nav>
          <h1>Welcome to the Home layout</h1>
          {children}
        </main>
        
      </body>
    </html>
  );
}
