import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'react';


const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "NextJS CRUD App",
  description: "Generated by create next app, SSR"
};

export default function RootLayout( { children } ) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href='/'>Home</Link>
          <Link href='/create'>Create Task</Link>
        </nav>
        <h1>Welcome to the Home layout</h1>
        <main> {children} </main>
      </body>
    </html>
  );
}
